# Config File for BRaVa Pilot Study Common Variant Conditional Analysis Pipeline on AoU

# Prerequisite
list_of_vcf_files: "afr_vcf_list.txt"
list_of_model_files: "afr_model_file_list.txt"
list_of_variance_ratio_files: "afr_variance_file_list.txt"
sparse_matrix: "conditioning_test/afr/mtx/allofus_array_afr_snp_wise_relatednessCutoff_0.05_5000_randomMarkersUsed.sparseGRM.mtx"
list_of_group_files: "afr_group_file_list.txt"

# Run name for output folders
run_name: "afr"

## Prerequisite: Don't need to change if using files/instructions provided in repo 
gene_trait_pairs_to_test: "/home/jupyter/common_condition/gene_pheno_test.csv"
protein_coding_region_bed: "/home/jupyter/common_condition/protein_coding_regions_hg38_no_padding_no_UTR_v39.bed"
phenotype_json: "/home/jupyter/common_condition/pilot_phenotypes.json"

# rule: id_variants_for_conditioning 
distance: 500000
maf:
  - 0.001
  - 0.0001
threads: 2 

# rule: spa_tests_conditional
min_mac: 0.5
annotations_to_include: "pLoF,damaging_missense,other_missense,synonymous,pLoF:damaging_missense,pLoF:damaging_missense:other_missense:synonymous"
