# Config File for BRaVa Pilot Study Common Variant Conditioninal Analysis Pipeline

# Prerequisite
list_of_vcf_files: "vcf_list.txt"
list_of_model_files: "model_file_list.txt"
variance_ratio_file: "variance_file_list.txt"
sparse_matrix: "test_files/test.sparseGRM.mtx"
group_file: "test_files/group_file.txt"

## Prerequisite: Don't need to change if using files/instructions provided in repo 
gene_trait_pairs_to_test: "gene_trait_pairs_for_conditioning.csv"
protein_coding_region_bed: "protein_coding_regions_hg38_no_padding_no_UTR_v47.bed"
phenotype_json: "pilot_phenotypes.json"

# id_variants_for_conditioning 
distance: 4000000
maf:
  - 0.01
  - 0.001
threads: 8 

# rule spa_tests_conditional
min_mac: 4
annotations_to_include: "pLoF,damaging_missense_or_protein_altering,other_missense_or_protein_altering,synonymous,pLoF:damaging_missense_or_protein_altering,pLoF:damaging_missense_or_protein_altering:other_missense_or_protein_altering:synonymous"
