# Config File for BRaVa Pilot Study Common Variant Conditional Analysis Pipeline

# Prerequisite
list_of_vcf_files: "vcf_list.txt"
list_of_model_files: "model_file_list.txt"
variance_ratio_file: "variance_file_list.txt"
sparse_matrix: "conditioning_test/allofus_array_eur_snp_wise_relatednessCutoff_0.05_5000_randomMarkersUsed.sparseGRM.mtx"
group_file: "conditioning_test/aou.v8.chr12.eur.variants_only.spliceai=0.20_cadd=28.1_revel=0.773.canonical.txt.gz"

## Prerequisite: Don't need to change if using files/instructions provided in repo 
gene_trait_pairs_to_test: "/home/jupyter/common_condition/gene_pheno_test.csv"
protein_coding_region_bed: "protein_coding_regions_hg38_no_padding_no_UTR_v39.bed"
phenotype_json: "pilot_phenotypes.json"

# rule: id_variants_for_conditioning 
distance: 500000
maf:
  - 0.001
  - 0.0001
threads: 2 

# rule: spa_tests_conditional
min_mac: 0.5
annotations_to_include: "pLoF,damaging_missense,other_missense,synonymous,pLoF:damaging_missense,pLoF:damaging_missense:other_missense:synonymous"